package domain

import (
	"time"

	"github.com/google/uuid"
)

// TransferState is the lifecycle marker for a Transfer row.
//
// The state machine deliberately has a single entry edge and two
// terminal sinks:
//
//	PENDING -> PROCESSED
//	PENDING -> FAILED
//
// PENDING is written by the service inside the same transaction that
// drives the transfer to a terminal state, so a successful committed
// read should never observe a PENDING row. The state column exists so
// an async/queued variant can be slotted in later without a schema
// change.
type TransferState string

const (
	// StatePending is the initial state on insert. Always replaced
	// before the surrounding transaction commits.
	StatePending TransferState = "PENDING"

	// StateProcessed is the terminal success state. The two ledger
	// entries (DEBIT + CREDIT) and the updated wallet balances are
	// already persisted by the time a transfer is in this state.
	StateProcessed TransferState = "PROCESSED"

	// StateFailed is the terminal failure state. The idempotency
	// record is still committed alongside it, so retries of the same
	// request return the same FAILED transfer rather than reattempting
	// the debit.
	StateFailed TransferState = "FAILED"
)

// Valid reports whether s is one of the three recognised state strings.
// It is used by the domain unit tests and as a defence-in-depth check
// before persisting a state value.
func (s TransferState) Valid() bool {
	switch s {
	case StatePending, StateProcessed, StateFailed:
		return true
	}
	return false
}

// CanTransitionTo enforces the allowed state machine. The legal edges
// are PENDING -> PROCESSED and PENDING -> FAILED; everything else is
// rejected.
//
// The repository layer also relies on the database CHECK constraint to
// reject invalid state values; this method is what the service layer
// asks before issuing the UPDATE.
func (s TransferState) CanTransitionTo(next TransferState) bool {
	if s == StatePending && (next == StateProcessed || next == StateFailed) {
		return true
	}
	return false
}

// Transfer is a request to move `Amount` minor units from one wallet to
// another. A Transfer row, two LedgerEntry rows, and (optionally) one
// IdempotencyRecord row are produced atomically by
// service.TransferService.Create.
//
// Field notes:
//
//   - ID is a UUID generated by the service layer. The repository never
//     sees a zero UUID — callers MUST set ID before Insert.
//
//   - FromWalletID and ToWalletID are wallet IDs (TEXT, see Wallet.ID).
//     The schema CHECK constraint enforces them to differ.
//
//   - Amount is positive (schema CHECK constraint plus service-level
//     Validate enforce this).
//
//   - State follows the state machine described on TransferState.
//
//   - FailureReason is set ONLY when State == StateFailed. The schema
//     stores it as a nullable TEXT column; the repository maps "" <->
//     SQL NULL so the Go zero value behaves as "no reason yet".
type Transfer struct {
	ID            uuid.UUID
	FromWalletID  string
	ToWalletID    string
	Amount        int64
	State         TransferState
	FailureReason string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
